import type { Category } from "@/app/page"

const wordsDatabase = {
  sustantivos: [
    "avión",
    "perro",
    "cuchara",
    "policía",
    "cama",
    "mesa",
    "silla",
    "ventana",
    "puerta",
    "libro",
    "teléfono",
    "computadora",
    "televisión",
    "refrigerador",
    "coche",
    "bicicleta",
    "zapato",
    "sombrero",
    "reloj",
    "llave",
    "botella",
    "vaso",
    "plato",
    "tenedor",
    "cuchillo",
    "lámpara",
    "espejo",
    "almohada",
    "manta",
    "toalla",
    "jabón",
    "cepillo",
    "peine",
    "tijeras",
    "bolígrafo",
    "lápiz",
    "papel",
    "sobre",
    "sello",
    "carta",
    "maleta",
    "mochila",
    "paraguas",
    "gafas",
    "collar",
    "anillo",
    "pulsera",
    "pendientes",
    "cinturón",
    "cartera",
    "moneda",
    "billete",
    "tarjeta",
    "foto",
    "cuadro",
    "florero",
    "planta",
    "flor",
    "árbol",
    "piedra",
    "arena",
    "agua",
    "fuego",
    "hielo",
    "nieve",
    "lluvia",
    "sol",
    "luna",
    "estrella",
    "nube",
    "montaña",
    "río",
    "mar",
    "lago",
    "isla",
    "puente",
    "edificio",
    "casa",
    "apartamento",
    "hotel",
    "restaurante",
    "café",
    "bar",
    "tienda",
    "mercado",
    "banco",
    "hospital",
    "escuela",
    "universidad",
    "biblioteca",
    "museo",
    "teatro",
    "cine",
    "parque",
    "jardín",
    "plaza",
    "calle",
    "avenida",
    "semáforo",
    "autobús",
  ],

  acciones: [
    "correr",
    "caminar",
    "saltar",
    "bailar",
    "cantar",
    "dormir",
    "comer",
    "beber",
    "cocinar",
    "limpiar",
    "lavar",
    "planchar",
    "barrer",
    "aspirar",
    "pintar",
    "dibujar",
    "escribir",
    "leer",
    "estudiar",
    "trabajar",
    "jugar",
    "reír",
    "llorar",
    "gritar",
    "susurrar",
    "hablar",
    "escuchar",
    "mirar",
    "ver",
    "tocar",
    "oler",
    "saborear",
    "sentir",
    "pensar",
    "recordar",
    "olvidar",
    "aprender",
    "enseñar",
    "explicar",
    "preguntar",
    "responder",
    "saludar",
    "despedirse",
    "abrazar",
    "besar",
    "sonreír",
    "guiñar",
    "aplaudir",
    "silbar",
    "tararear",
    "nadar",
    "bucear",
    "surfear",
    "esquiar",
    "patinar",
    "montar",
    "conducir",
    "volar",
    "navegar",
    "remar",
    "escalar",
    "trepar",
    "caer",
    "levantarse",
    "sentarse",
    "acostarse",
    "estirarse",
    "agacharse",
    "inclinarse",
    "girar",
    "empujar",
    "tirar",
    "levantar",
    "cargar",
    "soltar",
    "agarrar",
    "sostener",
    "lanzar",
    "atrapar",
    "golpear",
    "construir",
    "romper",
    "reparar",
    "arreglar",
    "decorar",
    "ordenar",
    "organizar",
    "buscar",
    "encontrar",
    "perder",
    "comprar",
    "vender",
    "pagar",
    "cobrar",
    "ahorrar",
    "gastar",
    "regalar",
    "recibir",
    "dar",
    "compartir",
  ],

  profesiones: [
    "doctor",
    "enfermero",
    "dentista",
    "veterinario",
    "farmacéutico",
    "psicólogo",
    "fisioterapeuta",
    "cirujano",
    "pediatra",
    "ginecólogo",
    "maestro",
    "profesor",
    "director",
    "bibliotecario",
    "tutor",
    "educador",
    "investigador",
    "científico",
    "biólogo",
    "químico",
    "ingeniero",
    "arquitecto",
    "constructor",
    "electricista",
    "plomero",
    "carpintero",
    "mecánico",
    "soldador",
    "pintor",
    "albañil",
    "abogado",
    "juez",
    "fiscal",
    "notario",
    "secretario",
    "contador",
    "economista",
    "banquero",
    "consultor",
    "analista",
    "policía",
    "bombero",
    "guardia",
    "militar",
    "detective",
    "espía",
    "guardaespaldas",
    "vigilante",
    "salvavidas",
    "paramédico",
    "chef",
    "cocinero",
    "camarero",
    "barista",
    "panadero",
    "pastelero",
    "carnicero",
    "pescadero",
    "frutero",
    "vendedor",
    "piloto",
    "azafata",
    "capitán",
    "marinero",
    "conductor",
    "taxista",
    "chofer",
    "repartidor",
    "cartero",
    "mensajero",
    "artista",
    "pintor",
    "escultor",
    "músico",
    "cantante",
    "bailarín",
    "actor",
    "director",
    "productor",
    "fotógrafo",
    "periodista",
    "reportero",
    "editor",
    "escritor",
    "traductor",
    "locutor",
    "presentador",
    "comentarista",
    "crítico",
    "blogger",
    "programador",
    "diseñador",
    "desarrollador",
    "técnico",
    "soporte",
    "administrador",
    "gerente",
    "supervisor",
    "coordinador",
    "asistente",
  ],

  animales: [
    "perro",
    "gato",
    "ratón",
    "conejo",
    "hamster",
    "cobaya",
    "hurón",
    "loro",
    "canario",
    "pez",
    "caballo",
    "vaca",
    "cerdo",
    "oveja",
    "cabra",
    "gallina",
    "gallo",
    "pato",
    "ganso",
    "pavo",
    "león",
    "tigre",
    "leopardo",
    "guepardo",
    "pantera",
    "jaguar",
    "puma",
    "lince",
    "gato montés",
    "lobo",
    "oso",
    "oso polar",
    "panda",
    "koala",
    "canguro",
    "wallaby",
    "ornitorrinco",
    "equidna",
    "wombat",
    "demonio de tasmania",
    "elefante",
    "rinoceronte",
    "hipopótamo",
    "jirafa",
    "cebra",
    "antílope",
    "gacela",
    "búfalo",
    "bisonte",
    "alce",
    "mono",
    "chimpancé",
    "gorila",
    "orangután",
    "lemur",
    "perezoso",
    "armadillo",
    "oso hormiguero",
    "tapir",
    "capibara",
    "serpiente",
    "cobra",
    "víbora",
    "pitón",
    "boa",
    "anaconda",
    "lagarto",
    "iguana",
    "gecko",
    "camaleón",
    "cocodrilo",
    "caimán",
    "tortuga",
    "galápago",
    "salamandra",
    "rana",
    "sapo",
    "tritón",
    "axolotl",
    "renacuajo",
    "águila",
    "halcón",
    "buitre",
    "cóndor",
    "búho",
    "lechuza",
    "cuervo",
    "paloma",
    "gaviota",
    "pelícano",
    "tiburón",
    "ballena",
    "delfín",
    "foca",
    "morsa",
    "nutria",
    "castor",
    "pingüino",
    "albatros",
    "flamenco",
  ],

  objetos: [
    "martillo",
    "destornillador",
    "llave inglesa",
    "alicates",
    "sierra",
    "taladro",
    "tornillo",
    "clavo",
    "tuerca",
    "arandela",
    "guitarra",
    "piano",
    "violín",
    "batería",
    "flauta",
    "trompeta",
    "saxofón",
    "armónica",
    "maracas",
    "tambor",
    "pelota",
    "balón",
    "raqueta",
    "bate",
    "guante",
    "casco",
    "patines",
    "bicicleta",
    "monopatín",
    "tabla de surf",
    "cámara",
    "lente",
    "trípode",
    "flash",
    "filtro",
    "memoria",
    "batería",
    "cargador",
    "cable",
    "adaptador",
    "maquillaje",
    "pintalabios",
    "rímel",
    "sombra",
    "base",
    "colorete",
    "pincel",
    "esponja",
    "espejo",
    "perfume",
    "collar",
    "pulsera",
    "anillo",
    "pendientes",
    "broche",
    "gemelos",
    "reloj",
    "cadena",
    "medalla",
    "dije",
    "maleta",
    "mochila",
    "bolso",
    "cartera",
    "monedero",
    "billetera",
    "tarjetero",
    "llavero",
    "paraguas",
    "bastón",
    "gafas",
    "lentillas",
    "gafas de sol",
    "lupa",
    "microscopio",
    "telescopio",
    "brújula",
    "mapa",
    "GPS",
    "linterna",
    "vela",
    "cerilla",
    "encendedor",
    "lámpara",
    "bombilla",
    "interruptor",
    "enchufe",
    "cable",
    "pila",
    "batería",
    "libro",
    "revista",
    "periódico",
    "cuaderno",
    "agenda",
    "calendario",
    "bolígrafo",
    "lápiz",
    "rotulador",
    "goma",
  ],

  personajes: [
    "Harry Potter",
    "Hermione Granger",
    "Ron Weasley",
    "Dumbledore",
    "Voldemort",
    "Snape",
    "Hagrid",
    "Dobby",
    "Sirius Black",
    "Draco Malfoy",
    "Superman",
    "Batman",
    "Wonder Woman",
    "Spider-Man",
    "Iron Man",
    "Hulk",
    "Thor",
    "Capitán América",
    "Wolverine",
    "Deadpool",
    "Mickey Mouse",
    "Minnie Mouse",
    "Donald Duck",
    "Goofy",
    "Pluto",
    "Chip",
    "Dale",
    "Scrooge McDuck",
    "Huey",
    "Dewey",
    "Shrek",
    "Fiona",
    "Burro",
    "Gato con Botas",
    "Farquaad",
    "Dragón",
    "Pinocho",
    "Hada Madrina",
    "Príncipe Encantador",
    "Gingy",
    "Messi",
    "Cristiano Ronaldo",
    "Neymar",
    "Mbappé",
    "Haaland",
    "Benzema",
    "Modric",
    "Ramos",
    "Piqué",
    "Iniesta",
    "Einstein",
    "Newton",
    "Darwin",
    "Galileo",
    "Tesla",
    "Edison",
    "Curie",
    "Hawking",
    "Jobs",
    "Gates",
    "Frida Kahlo",
    "Picasso",
    "Van Gogh",
    "Da Vinci",
    "Monet",
    "Dalí",
    "Warhol",
    "Banksy",
    "Botero",
    "Rivera",
    "Beethoven",
    "Mozart",
    "Bach",
    "Chopin",
    "Vivaldi",
    "Tchaikovsky",
    "Brahms",
    "Debussy",
    "Ravel",
    "Stravinsky",
    "Chaplin",
    "Monroe",
    "Brando",
    "Hepburn",
    "Dean",
    "Bogart",
    "Garbo",
    "Grant",
    "Stewart",
    "Wayne",
    "Cervantes",
    "Shakespeare",
    "Borges",
    "García Márquez",
    "Neruda",
    "Lorca",
    "Machado",
    "Unamuno",
    "Cortázar",
    "Vargas Llosa",
  ],

  entretenimiento: [
    "Titanic",
    "Avatar",
    "Avengers",
    "Star Wars",
    "Jurassic Park",
    "Matrix",
    "Terminator",
    "Alien",
    "Predator",
    "Rocky",
    "El Padrino",
    "Casablanca",
    "Ciudadano Kane",
    "Psicosis",
    "Vertigo",
    "La Ventana Indiscreta",
    "Con la Muerte en los Talones",
    "Notorious",
    "Rebecca",
    "Los Pájaros",
    "El Señor de los Anillos",
    "Harry Potter",
    "Piratas del Caribe",
    "Indiana Jones",
    "Back to the Future",
    "E.T.",
    "Jaws",
    "Superman",
    "Batman",
    "Spider-Man",
    "Game of Thrones",
    "Breaking Bad",
    "The Walking Dead",
    "Friends",
    "The Office",
    "Stranger Things",
    "Lost",
    "Prison Break",
    "24",
    "House",
    "La Casa de Papel",
    "Élite",
    "Vis a Vis",
    "El Internado",
    "Águila Roja",
    "Gran Hotel",
    "Velvet",
    "Las Chicas del Cable",
    "Paquita Salas",
    "La que se Avecina",
    "Don Quijote",
    "Cien Años de Soledad",
    "El Principito",
    "1984",
    "Rebelión en la Granja",
    "Matar a un Ruiseñor",
    "El Gran Gatsby",
    "Orgullo y Prejuicio",
    "Jane Eyre",
    "Cumbres Borrascosas",
    "Bohemian Rhapsody",
    "Imagine",
    "Yesterday",
    "Hey Jude",
    "Let It Be",
    "Stairway to Heaven",
    "Hotel California",
    "Sweet Child O' Mine",
    "Smells Like Teen Spirit",
    "Billie Jean",
    "Despacito",
    "Macarena",
    "La Bamba",
    "Bamboléo",
    "Pobre Diabla",
    "Vivir Mi Vida",
    "La Tortura",
    "Hips Don't Lie",
    "Waka Waka",
    "Chantaje",
    "Fortnite",
    "Minecraft",
    "Among Us",
    "Call of Duty",
    "FIFA",
    "Grand Theft Auto",
    "Super Mario",
    "The Legend of Zelda",
    "Pokémon",
    "Pac-Man",
    "Netflix",
    "Disney+",
    "Amazon Prime",
    "HBO Max",
    "Apple TV+",
    "Spotify",
    "YouTube",
    "TikTok",
    "Instagram",
    "Facebook",
  ],

  lugares: [
    "playa",
    "montaña",
    "bosque",
    "desierto",
    "selva",
    "pradera",
    "valle",
    "colina",
    "acantilado",
    "cueva",
    "hospital",
    "escuela",
    "universidad",
    "biblioteca",
    "museo",
    "teatro",
    "cine",
    "estadio",
    "gimnasio",
    "piscina",
    "restaurante",
    "café",
    "bar",
    "discoteca",
    "hotel",
    "hostal",
    "camping",
    "resort",
    "spa",
    "casino",
    "banco",
    "oficina",
    "fábrica",
    "almacén",
    "taller",
    "laboratorio",
    "estudio",
    "consulta",
    "clínica",
    "farmacia",
    "supermercado",
    "tienda",
    "centro comercial",
    "mercado",
    "feria",
    "bazar",
    "boutique",
    "librería",
    "floristería",
    "panadería",
    "parque",
    "jardín",
    "plaza",
    "avenida",
    "calle",
    "callejón",
    "paseo",
    "boulevard",
    "ronda",
    "glorieta",
    "aeropuerto",
    "estación",
    "puerto",
    "terminal",
    "andén",
    "muelle",
    "embarcadero",
    "helipuerto",
    "hangar",
    "pista",
    "iglesia",
    "catedral",
    "mezquita",
    "sinagoga",
    "templo",
    "monasterio",
    "convento",
    "cementerio",
    "mausoleo",
    "cripta",
    "castillo",
    "palacio",
    "fortaleza",
    "torre",
    "muralla",
    "puente",
    "túnel",
    "viaducto",
    "acueducto",
    "presa",
    "zoológico",
    "acuario",
    "planetarium",
    "observatorio",
    "jardín botánico",
    "parque temático",
    "circo",
    "feria",
    "carnaval",
    "festival",
  ],
}

export function getRandomWord(enabledCategories: Category[]): { word: string; category: string } {
  const availableWords: { word: string; category: string }[] = []

  enabledCategories.forEach((category) => {
    const categoryWords = wordsDatabase[category.id as keyof typeof wordsDatabase] || []
    categoryWords.forEach((word) => {
      availableWords.push({ word, category: category.name })
    })
  })

  if (availableWords.length === 0) {
    return { word: "Error: No hay palabras disponibles", category: "Error" }
  }

  const randomIndex = Math.floor(Math.random() * availableWords.length)
  return availableWords[randomIndex]
}

export function getTotalWords(): number {
  return Object.values(wordsDatabase).reduce((total, words) => total + words.length, 0)
}
